### ISSUE TITLE
Several worlds still have old rotations

### ISSUE THREAD

**Issue by tsampazk** [aidudezzz/deepworlds#58]
### CartPole Discrete
---
- [x] `cartPoleWorldEmitterReceiver.wbt` new fixed one works ok, but uses NUE coordinate system, instead of [ENU which is default](https://cyberbotics.com/doc/reference/worldinfo) (fix in #60)
- [x] `cartPoleWorldRobotSupervisor.wbt` is not updated at all - broken (fix in #66)
- [x] `cartPoleWorldRobotSupervisorStableBaselines.wbt` is not updated at all - broken (fix in #71)
---
### CartPole Continuous
- [x] `cartPoleWorldEmitterReceiver.wbt` is not updated at all - broken (fixed in #59)
- [x] `cartPoleWorldRobotSupervisor.wbt` is not updated at all - broken (fixed in #67)
---
### Find and Avoid
- [x] `smallWorld.wbt` is not updated at all, automatic rotation resolver partially fixes it (fix in #63 - Thank you @KelvinYang0320)
---
### KHR-3HV
- [x] `khr-3hv.wbt` is not updated at all, seems to be working correctly (fix in #76 , along with a wealth of quality improvements)
---
### Panda Goal Reaching
- [x] `pandaRL_training.wbt` is not updated at all, seems to be working correctly (fix in #61 - Thank you @KelvinYang0320)
---
### Pit Escape
- [x] `pit_escape.wbt` fixed in #56 and works ok, but still uses NUE coordinate system, instead of ENU (same as cartpole emitter-receiver discrete)

**Comment by KelvinYang0320** [comment]
@tsampazk Shall we update all examples to ENU for [R2022a axis conventions](https://www.cyberbotics.com/doc/blog/Webots-2022-a-release?tab-language=python)?
Or just make sure these examples work correctly in NUE ?

**Comment by tsampazk** [comment]
> @tsampazk Shall we update all examples to ENU for [R2022a axis conventions](https://www.cyberbotics.com/doc/blog/Webots-2022-a-release?tab-language=python)? Or just make sure these examples work correctly in NUE ?

Hey @KelvinYang0320! I think that there is no reason to use a coordinate system other than the default one. It's a little bit of an extra effort to change it now, but it might avoid confusion for users moving forward.

**Comment by KelvinYang0320** [comment]
>Hey @KelvinYang0320! I think that there is no reason to use a coordinate system other than the default one. It's a little bit of an extra effort to change it now, but it might avoid confusion for users moving forward.

Ok, got it. 😃
I will also spend some time to update them.

**Comment by tsampazk** [comment]
Thank you very much, i will stick to cartpole and pit escape for now, so feel free to look into the remaining ones. :)
