### ISSUE TITLE
Update all reset methods to use new Webots capabilities

### ISSUE THREAD

**Issue by tsampazk** [aidudezzz/deepworlds#8]
Webots 2020a rev2 will fix some issues related to resetting the Webots world without resetting the controllers (https://cyberbotics.com/doc/reference/supervisor#wb_supervisor_simulation_reset).

When the new version is released deepworlds examples should use this method to reset the world instead of reloading the robot node.

See https://github.com/aidudezzz/deepbots/issues/25

- [x] Find and avoid
- [x] KHR-3HV
- [x] Franka Emika Panda
- [ ] Pit Escape (#56)
- [x] Cartpole emitter-receiver discrete
- [x] Cartpole emitter-receiver continuous (#59)

**Comment by tsampazk** [comment]
Reset is currently having issues with the emitter/receiver scheme, see https://github.com/aidudezzz/deepbots/issues/51
